/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    int x = 210;    //chieu rong
    int y = 600;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        HOMEPAGE.setVisible(true);
        ACCOUNTstudent.setVisible(false);
        Slide_menu.setSize(210,600);
    }

    public void openMenu() {
        Slide_menu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 210; i++) {
                            Slide_menu.setSize(i, y);
                            Thread.sleep(1,5);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 210;
        }
    }

    public void closeMenu() {
        Slide_menu.setSize(x, y);
        if (x == 210) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 210; i >= 0; i--) {
                            Slide_menu.setSize(i, y);
                            Thread.sleep(1,5);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTotal = new javax.swing.JPanel();
        Tittle_font = new javax.swing.JPanel();
        Slide_menu = new javax.swing.JPanel();
        Include_icon = new javax.swing.JPanel();
        Closemenu = new javax.swing.JLabel();
        Icon_app = new javax.swing.JLabel();
        HOMEPAGE_menuslide = new javax.swing.JLabel();
        ACCOUNTstudent_menuslide = new javax.swing.JLabel();
        UPDATE_menuslide = new javax.swing.JLabel();
        LOGOUT_menuslide = new javax.swing.JLabel();
        CLASSMANAGE_menuslide = new javax.swing.JLabel();
        GRADEMANAGE_menuslide = new javax.swing.JLabel();
        CLASSFICATION_menuslide1 = new javax.swing.JLabel();
        Separator_Menuslide = new javax.swing.JSeparator();
        MenuBar = new javax.swing.JPanel();
        OpenMenuicon = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        HOMEPAGE = new javax.swing.JPanel();
        Homepage_tittle = new javax.swing.JLabel();
        ACCOUNTstudent = new javax.swing.JPanel();
        Account_tittle = new javax.swing.JLabel();
        UPDATE = new javax.swing.JPanel();
        Update_tittle = new javax.swing.JLabel();
        CLASSMANAGE = new javax.swing.JPanel();
        Classmanage_tittle = new javax.swing.JLabel();
        GRADEMANAGE = new javax.swing.JPanel();
        Grademanage_tittle = new javax.swing.JLabel();
        CLASSFICATION = new javax.swing.JPanel();
        Classfication_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelTotal.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tittle_font.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout Tittle_fontLayout = new javax.swing.GroupLayout(Tittle_font);
        Tittle_font.setLayout(Tittle_fontLayout);
        Tittle_fontLayout.setHorizontalGroup(
            Tittle_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        Tittle_fontLayout.setVerticalGroup(
            Tittle_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelTotal.add(Tittle_font, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        Slide_menu.setBackground(new java.awt.Color(0, 102, 102));
        Slide_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Slide_menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Slide_menu.setPreferredSize(new java.awt.Dimension(190, 590));
        Slide_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Include_icon.setBackground(new java.awt.Color(255, 255, 255));
        Include_icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Closemenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Closemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closemenu.setText("X");
        Closemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosemenuMouseClicked(evt);
            }
        });

        Icon_app.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/scholar.png"))); // NOI18N

        javax.swing.GroupLayout Include_iconLayout = new javax.swing.GroupLayout(Include_icon);
        Include_icon.setLayout(Include_iconLayout);
        Include_iconLayout.setHorizontalGroup(
            Include_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Include_iconLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Closemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Include_iconLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Icon_app)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Include_iconLayout.setVerticalGroup(
            Include_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Include_iconLayout.createSequentialGroup()
                .addComponent(Closemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Icon_app)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Slide_menu.add(Include_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        HOMEPAGE_menuslide.setBackground(new java.awt.Color(255, 255, 255));
        HOMEPAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HOMEPAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        HOMEPAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOMEPAGE_menuslide.setText("Trang Chủ");
        HOMEPAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEPAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(HOMEPAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 30));

        ACCOUNTstudent_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ACCOUNTstudent_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        ACCOUNTstudent_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ACCOUNTstudent_menuslide.setText("Thêm Sinh Viên");
        ACCOUNTstudent_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACCOUNTstudent_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(ACCOUNTstudent_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 30));

        UPDATE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UPDATE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_menuslide.setText("Tìm Kiếm - Cập Nhập");
        UPDATE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(UPDATE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 30));

        LOGOUT_menuslide.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LOGOUT_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUT_menuslide.setText("Đăng Xuất");
        Slide_menu.add(LOGOUT_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 210, 30));

        CLASSMANAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLASSMANAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        CLASSMANAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLASSMANAGE_menuslide.setText("Quản lý lớp");
        CLASSMANAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLASSMANAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(CLASSMANAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 210, 30));

        GRADEMANAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GRADEMANAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        GRADEMANAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GRADEMANAGE_menuslide.setText("Quản lý điểm");
        GRADEMANAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRADEMANAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(GRADEMANAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 30));

        CLASSFICATION_menuslide1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLASSFICATION_menuslide1.setForeground(new java.awt.Color(255, 255, 255));
        CLASSFICATION_menuslide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLASSFICATION_menuslide1.setText("Phân Loại");
        CLASSFICATION_menuslide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLASSFICATION_menuslide1MouseClicked(evt);
            }
        });
        Slide_menu.add(CLASSFICATION_menuslide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 30));
        Slide_menu.add(Separator_Menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 10));

        PanelTotal.add(Slide_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 0, -1));

        MenuBar.setBackground(new java.awt.Color(255, 255, 255));

        OpenMenuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/menu.png"))); // NOI18N
        OpenMenuicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMenuiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(OpenMenuicon)
                .addContainerGap(884, Short.MAX_VALUE))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenMenuicon)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelTotal.add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 940, 60));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new java.awt.CardLayout());

        HOMEPAGE.setBackground(new java.awt.Color(255, 255, 255));

        Homepage_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Homepage_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Homepage_tittle.setText("TRANG CHỦ");

        javax.swing.GroupLayout HOMEPAGELayout = new javax.swing.GroupLayout(HOMEPAGE);
        HOMEPAGE.setLayout(HOMEPAGELayout);
        HOMEPAGELayout.setHorizontalGroup(
            HOMEPAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPAGELayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(Homepage_tittle)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        HOMEPAGELayout.setVerticalGroup(
            HOMEPAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPAGELayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Homepage_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(483, Short.MAX_VALUE))
        );

        Main.add(HOMEPAGE, "card2");

        ACCOUNTstudent.setBackground(new java.awt.Color(255, 255, 255));

        Account_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Account_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Account_tittle.setText("TÀI KHOẢN");

        javax.swing.GroupLayout ACCOUNTstudentLayout = new javax.swing.GroupLayout(ACCOUNTstudent);
        ACCOUNTstudent.setLayout(ACCOUNTstudentLayout);
        ACCOUNTstudentLayout.setHorizontalGroup(
            ACCOUNTstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNTstudentLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(Account_tittle)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        ACCOUNTstudentLayout.setVerticalGroup(
            ACCOUNTstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNTstudentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Account_tittle)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        Main.add(ACCOUNTstudent, "card3");

        UPDATE.setBackground(new java.awt.Color(255, 255, 255));

        Update_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Update_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Update_tittle.setText("TÌM KIẾM -CẬP NHẬP");

        javax.swing.GroupLayout UPDATELayout = new javax.swing.GroupLayout(UPDATE);
        UPDATE.setLayout(UPDATELayout);
        UPDATELayout.setHorizontalGroup(
            UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPDATELayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(Update_tittle)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        UPDATELayout.setVerticalGroup(
            UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPDATELayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Update_tittle)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        Main.add(UPDATE, "card4");

        CLASSMANAGE.setBackground(new java.awt.Color(255, 255, 255));
        CLASSMANAGE.setForeground(new java.awt.Color(255, 255, 255));

        Classmanage_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Classmanage_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Classmanage_tittle.setText("QUẢN LÝ LỚP");

        javax.swing.GroupLayout CLASSMANAGELayout = new javax.swing.GroupLayout(CLASSMANAGE);
        CLASSMANAGE.setLayout(CLASSMANAGELayout);
        CLASSMANAGELayout.setHorizontalGroup(
            CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLASSMANAGELayout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(Classmanage_tittle)
                .addGap(375, 375, 375))
        );
        CLASSMANAGELayout.setVerticalGroup(
            CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSMANAGELayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Classmanage_tittle)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        Main.add(CLASSMANAGE, "card6");

        GRADEMANAGE.setBackground(new java.awt.Color(255, 255, 255));
        GRADEMANAGE.setForeground(new java.awt.Color(255, 255, 255));

        Grademanage_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Grademanage_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Grademanage_tittle.setText("QUẢN LÝ ĐIỂM");

        javax.swing.GroupLayout GRADEMANAGELayout = new javax.swing.GroupLayout(GRADEMANAGE);
        GRADEMANAGE.setLayout(GRADEMANAGELayout);
        GRADEMANAGELayout.setHorizontalGroup(
            GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GRADEMANAGELayout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addComponent(Grademanage_tittle)
                .addGap(399, 399, 399))
        );
        GRADEMANAGELayout.setVerticalGroup(
            GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GRADEMANAGELayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Grademanage_tittle)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        Main.add(GRADEMANAGE, "card7");

        CLASSFICATION.setBackground(new java.awt.Color(255, 255, 255));

        Classfication_title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Classfication_title.setForeground(new java.awt.Color(0, 102, 102));
        Classfication_title.setText("PHÂN LOẠI");

        javax.swing.GroupLayout CLASSFICATIONLayout = new javax.swing.GroupLayout(CLASSFICATION);
        CLASSFICATION.setLayout(CLASSFICATIONLayout);
        CLASSFICATIONLayout.setHorizontalGroup(
            CLASSFICATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSFICATIONLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(Classfication_title)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        CLASSFICATIONLayout.setVerticalGroup(
            CLASSFICATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSFICATIONLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Classfication_title)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        Main.add(CLASSFICATION, "card5");

        PanelTotal.add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 940, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClosemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosemenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_ClosemenuMouseClicked
        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Slide_menu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void HOMEPAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEPAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(true);
        ACCOUNTstudent.setVisible(false);
        UPDATE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_HOMEPAGE_menuslideMouseClicked

    private void ACCOUNTstudent_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACCOUNTstudent_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTstudent.setVisible(true);
        UPDATE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_ACCOUNTstudent_menuslideMouseClicked

    private void OpenMenuiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMenuiconMouseClicked
        openMenu();
    }//GEN-LAST:event_OpenMenuiconMouseClicked

    private void UPDATE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATE_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTstudent.setVisible(false);
        UPDATE.setVisible(true);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_UPDATE_menuslideMouseClicked

    private void CLASSMANAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLASSMANAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTstudent.setVisible(false);
        UPDATE.setVisible(false);
        CLASSMANAGE.setVisible(true);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_CLASSMANAGE_menuslideMouseClicked

    private void CLASSFICATION_menuslide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLASSFICATION_menuslide1MouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTstudent.setVisible(false);
        UPDATE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(true);
        closeMenu();
    }//GEN-LAST:event_CLASSFICATION_menuslide1MouseClicked

    private void GRADEMANAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRADEMANAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTstudent.setVisible(false);
        UPDATE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(true);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_GRADEMANAGE_menuslideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACCOUNTstudent;
    private javax.swing.JLabel ACCOUNTstudent_menuslide;
    private javax.swing.JLabel Account_tittle;
    private javax.swing.JPanel CLASSFICATION;
    private javax.swing.JLabel CLASSFICATION_menuslide1;
    private javax.swing.JPanel CLASSMANAGE;
    private javax.swing.JLabel CLASSMANAGE_menuslide;
    private javax.swing.JLabel Classfication_title;
    private javax.swing.JLabel Classmanage_tittle;
    private javax.swing.JLabel Closemenu;
    private javax.swing.JPanel GRADEMANAGE;
    private javax.swing.JLabel GRADEMANAGE_menuslide;
    private javax.swing.JLabel Grademanage_tittle;
    private javax.swing.JPanel HOMEPAGE;
    private javax.swing.JLabel HOMEPAGE_menuslide;
    private javax.swing.JLabel Homepage_tittle;
    private javax.swing.JLabel Icon_app;
    private javax.swing.JPanel Include_icon;
    private javax.swing.JLabel LOGOUT_menuslide;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel OpenMenuicon;
    private javax.swing.JPanel PanelTotal;
    private javax.swing.JSeparator Separator_Menuslide;
    private javax.swing.JPanel Slide_menu;
    private javax.swing.JPanel Tittle_font;
    private javax.swing.JPanel UPDATE;
    private javax.swing.JLabel UPDATE_menuslide;
    private javax.swing.JLabel Update_tittle;
    // End of variables declaration//GEN-END:variables
}
